spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/exemplo_security
    password: dbaaccesskey
    username: postgres
    driverClassName: org.postgresql.Driver